# Generated by Django 5.0.6 on 2026-02-14 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Objet de la demande')),
                ('message', models.TextField(verbose_name='Message / détails de la demande')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('sent', 'Devis envoyé'), ('closed', 'Clôturé')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notes admin (interne)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Demande de devis',
                'verbose_name_plural': 'Demandes de devis',
                'db_table': 'quotes_quoterequest',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuoteRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité demandée')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_request_items', to='catalog.product', verbose_name='Produit')),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quoterequest', verbose_name='Demande de devis')),
            ],
            options={
                'verbose_name': 'Ligne de demande',
                'verbose_name_plural': 'Lignes de demande',
                'db_table': 'quotes_quoterequestitem',
            },
        ),
    ]
