# Generated by Django 5.0.6 on 2026-02-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processed', 'Traité'), ('sent', 'Devis envoyé'), ('closed', 'Clôturé')], default='pending', max_length=20),
        ),
    ]
