# Generated by Django 5.0.6 on 2026-08-11 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('login_failed', 'Échec de connexion'), ('status_change', 'Changement de statut'), ('permission_change', 'Changement de permissions'), ('export', 'Export de données'), ('other', 'Autre')], db_index=True, max_length=32, verbose_name='Action')),
                ('actor_label', models.CharField(blank=True, help_text="Instantané du nom/email de l'auteur au moment de l'action : le journal reste lisible même si le compte est supprimé.", max_length=255, verbose_name='Auteur (libellé)')),
                ('object_id', models.CharField(blank=True, help_text='Clé primaire sous forme de texte (supporte entiers, UUID, etc.).', max_length=64, verbose_name="Identifiant de l'objet")),
                ('object_repr', models.CharField(blank=True, help_text="Instantané de l'objet au moment de l'action (ex. « Produit REF-102 »).", max_length=255, verbose_name='Objet (libellé)')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Format : {"nom_du_champ": {"avant": ..., "apres": ...}}', verbose_name='Modifications')),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Informations libres (motif, URL, identifiant tenté, etc.).', verbose_name='Contexte supplémentaire')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=400, verbose_name='Navigateur')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name="Type d'objet")),
            ],
            options={
                'verbose_name': "Entrée d'audit",
                'verbose_name_plural': "Journal d'audit",
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='audit_actor_created_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_object_idx'), models.Index(fields=['action', '-created_at'], name='audit_action_created_idx')],
            },
        ),
    ]
