# Generated by Django 5.0.6 on 2026-02-14 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Référence')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantité en stock')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Prix unitaire (devise locale)', max_digits=12, verbose_name='Prix unitaire')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/products/%Y/%m/', verbose_name='Image du produit')),
                ('alert_threshold', models.PositiveIntegerField(default=5, help_text='Alerte email si stock <= ce seuil', verbose_name="Seuil d'alerte stock")),
                ('is_visible', models.BooleanField(default=True, help_text='Si coché, le produit apparaît sur le site vitrine.', verbose_name='Visible sur le site client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'catalog_product',
                'ordering': ('reference',),
                'permissions': [('manage_stock', 'Peut gérer les mouvements de stock (sortie/entrée)')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie')], max_length=3)),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('note', models.CharField(blank=True, help_text='Ex. : Vente, Réception, Correction, etc.', max_length=255, verbose_name='Motif / note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'db_table': 'catalog_stockmovement',
                'ordering': ('-created_at',),
            },
        ),
    ]
