# Generated by Django 5.0.6 on 2026-02-15 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('reference',), 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
    ]
