# Generated by Django 5.0.6 on 2026-03-12 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_manage_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/products/360/%Y/%m/', verbose_name='Image')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Les images seront affichées dans cet ordre lors de la rotation 360°.', verbose_name='Ordre')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_360', to='catalog.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Image 360°',
                'verbose_name_plural': 'Images 360°',
                'db_table': 'catalog_productimage',
                'ordering': ('product', 'order'),
            },
        ),
    ]
